/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.wstore.views;

import com.wstore.views.thuoctinhsanpham.FormChatLieuDayJDialog;
import com.wstore.views.thuoctinhsanpham.FormChatLieuKinhJDialog;
import com.wstore.views.thuoctinhsanpham.FormChatLieuVoJDialog;
import com.wstore.views.thuoctinhsanpham.FormDongMayJDialog;
import com.wstore.views.thuoctinhsanpham.FormDongSanPhamJDialog;
import com.wstore.views.thuoctinhsanpham.FormMauJDialog;
import com.wstore.views.thuoctinhsanpham.FormThuongHieuJDialog;
import com.wstore.views.thuoctinhsanpham.FormTinhNangJDialog;
import com.wstore.views.thuoctinhsanpham.FormXuatXuJDialog;

/**
 *
 * @author ducan
 */
public class FormTabThuocTinhSanPham extends javax.swing.JPanel {

    /**
     * Creates new form FormTabThuocTinhSanPham
     */
    public FormTabThuocTinhSanPham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThuongHieu = new javax.swing.JButton();
        btnDongSanPham = new javax.swing.JButton();
        btnDongMay = new javax.swing.JButton();
        btnChatLieuDay = new javax.swing.JButton();
        btnChatLieuKinh = new javax.swing.JButton();
        btnXuatXu = new javax.swing.JButton();
        btnChatLieuVo = new javax.swing.JButton();
        btnMau = new javax.swing.JButton();
        btnTinhNang = new javax.swing.JButton();

        setBackground(new java.awt.Color(241, 246, 251));
        setLayout(new java.awt.GridLayout(4, 4, 20, 20));

        btnThuongHieu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThuongHieu.setText("Thương hiệu");
        btnThuongHieu.setIconTextGap(10);
        btnThuongHieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuongHieuActionPerformed(evt);
            }
        });
        add(btnThuongHieu);

        btnDongSanPham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDongSanPham.setText("Dòng sản phẩm");
        btnDongSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongSanPhamActionPerformed(evt);
            }
        });
        add(btnDongSanPham);

        btnDongMay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDongMay.setText("Dòng máy");
        btnDongMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongMayActionPerformed(evt);
            }
        });
        add(btnDongMay);

        btnChatLieuDay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnChatLieuDay.setText("Chất liệu dây");
        btnChatLieuDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatLieuDayActionPerformed(evt);
            }
        });
        add(btnChatLieuDay);

        btnChatLieuKinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnChatLieuKinh.setText("Chất liệu kính");
        btnChatLieuKinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatLieuKinhActionPerformed(evt);
            }
        });
        add(btnChatLieuKinh);

        btnXuatXu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXuatXu.setText("Xuất xứ ");
        btnXuatXu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnXuatXu.setIconTextGap(10);
        btnXuatXu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatXuActionPerformed(evt);
            }
        });
        add(btnXuatXu);

        btnChatLieuVo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnChatLieuVo.setText("Chất liệu vỏ");
        btnChatLieuVo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatLieuVoActionPerformed(evt);
            }
        });
        add(btnChatLieuVo);

        btnMau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMau.setText("Màu");
        btnMau.setIconTextGap(10);
        btnMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMauActionPerformed(evt);
            }
        });
        add(btnMau);

        btnTinhNang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTinhNang.setText("Tính năng");
        btnTinhNang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhNangActionPerformed(evt);
            }
        });
        add(btnTinhNang);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThuongHieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuongHieuActionPerformed
        new FormThuongHieuJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_btnThuongHieuActionPerformed

    private void btnDongSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongSanPhamActionPerformed
        new FormDongSanPhamJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_btnDongSanPhamActionPerformed

    private void btnDongMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongMayActionPerformed
        new FormDongMayJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_btnDongMayActionPerformed

    private void btnChatLieuDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatLieuDayActionPerformed
        new FormChatLieuDayJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_btnChatLieuDayActionPerformed

    private void btnChatLieuKinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatLieuKinhActionPerformed
        new FormChatLieuKinhJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_btnChatLieuKinhActionPerformed

    private void btnXuatXuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatXuActionPerformed
        new FormXuatXuJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_btnXuatXuActionPerformed

    private void btnChatLieuVoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatLieuVoActionPerformed
        new FormChatLieuVoJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_btnChatLieuVoActionPerformed

    private void btnMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMauActionPerformed
        new FormMauJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_btnMauActionPerformed

    private void btnTinhNangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhNangActionPerformed
        new FormTinhNangJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_btnTinhNangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChatLieuDay;
    private javax.swing.JButton btnChatLieuKinh;
    private javax.swing.JButton btnChatLieuVo;
    private javax.swing.JButton btnDongMay;
    private javax.swing.JButton btnDongSanPham;
    private javax.swing.JButton btnMau;
    private javax.swing.JButton btnThuongHieu;
    private javax.swing.JButton btnTinhNang;
    private javax.swing.JButton btnXuatXu;
    // End of variables declaration//GEN-END:variables
}
